-- Therapy model schema for Supabase (Postgres)
-- Run in Supabase SQL editor or via migration tooling.

create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'therapy_activity_type') then
    create type therapy_activity_type as enum (
      'warmup_word',
      'word_practice',
      'question_mcq',
      'question_open'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'therapy_item_type') then
    create type therapy_item_type as enum ('word', 'question');
  end if;

  if not exists (select 1 from pg_type where typname = 'tongue_position') then
    create type tongue_position as enum ('front', 'middle', 'back');
  end if;

  if not exists (select 1 from pg_type where typname = 'therapy_difficulty') then
    create type therapy_difficulty as enum ('beginner', 'intermediate', 'advanced');
  end if;
end $$;

create table if not exists therapy_levels (
  id smallint generated by default as identity primary key,
  name text not null unique,
  description text,
  min_age smallint check (min_age is null or min_age >= 0),
  max_age smallint check (max_age is null or max_age >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (min_age is null or max_age is null or min_age <= max_age)
);

create table if not exists therapy_activities (
  id uuid primary key default gen_random_uuid(),
  level_id smallint not null references therapy_levels(id) on delete cascade,
  type therapy_activity_type not null,
  title text not null,
  target_letter text,
  difficulty therapy_difficulty,
  order_index integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (order_index >= 0)
);

create unique index if not exists therapy_activities_level_order_uq
  on therapy_activities(level_id, order_index);

create index if not exists therapy_activities_level_idx
  on therapy_activities(level_id);

create table if not exists therapy_items (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null references therapy_activities(id) on delete cascade,
  item_type therapy_item_type not null,
  payload_json jsonb not null,
  order_index integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (order_index >= 0),
  check (jsonb_typeof(payload_json) = 'object')
);

create unique index if not exists therapy_items_activity_order_uq
  on therapy_items(activity_id, order_index);

create index if not exists therapy_items_activity_idx
  on therapy_items(activity_id);

create index if not exists therapy_items_payload_gin
  on therapy_items using gin (payload_json);

create table if not exists tongue_placements (
  id smallint generated by default as identity primary key,
  position tongue_position not null,
  description text,
  visual_guide text,
  emoji_hint text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists therapy_levels_set_updated_at on therapy_levels;
create trigger therapy_levels_set_updated_at
  before update on therapy_levels
  for each row execute procedure set_updated_at();

drop trigger if exists therapy_activities_set_updated_at on therapy_activities;
create trigger therapy_activities_set_updated_at
  before update on therapy_activities
  for each row execute procedure set_updated_at();

drop trigger if exists therapy_items_set_updated_at on therapy_items;
create trigger therapy_items_set_updated_at
  before update on therapy_items
  for each row execute procedure set_updated_at();

drop trigger if exists tongue_placements_set_updated_at on tongue_placements;
create trigger tongue_placements_set_updated_at
  before update on tongue_placements
  for each row execute procedure set_updated_at();
